// <auto-generated />
using System;
using HRApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HRApp.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20241119212403_TimeOffRequests")]
    partial class TimeOffRequests
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("HRApp.Models.CalendarEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("End")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCompanyWide")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Start")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("CalendarEvents");
                });

            modelBuilder.Entity("HRApp.Models.Employees", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Department")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LeaveDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Salary")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Employee", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 999,
                            Department = "Software Engineering",
                            Email = "admin@hrapp.co.uk",
                            FirstName = "Admin",
                            Gender = "None",
                            JoinDate = new DateTime(2022, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Account",
                            Salary = "£999999.00"
                        },
                        new
                        {
                            Id = 1,
                            Department = "Software Engineering",
                            Email = "schen@company.com",
                            FirstName = "Sarah",
                            Gender = "Female",
                            JoinDate = new DateTime(2022, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Chen",
                            Salary = "£65000.00"
                        },
                        new
                        {
                            Id = 2,
                            Department = "Software Engineering",
                            Email = "jwilson@company.com",
                            FirstName = "James",
                            Gender = "Male",
                            JoinDate = new DateTime(2022, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Wilson",
                            Salary = "£62000.00"
                        },
                        new
                        {
                            Id = 3,
                            Department = "Product Management",
                            Email = "epatel@company.com",
                            FirstName = "Emily",
                            Gender = "Female",
                            JoinDate = new DateTime(2022, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Patel",
                            Salary = "£68000.00"
                        },
                        new
                        {
                            Id = 4,
                            Department = "Sales",
                            Email = "mthompson@company.com",
                            FirstName = "Michael",
                            Gender = "Male",
                            JoinDate = new DateTime(2022, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Thompson",
                            LeaveDate = new DateTime(2023, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Salary = "£55000.00"
                        },
                        new
                        {
                            Id = 5,
                            Department = "Marketing",
                            Email = "jkumar@company.com",
                            FirstName = "Jessica",
                            Gender = "Female",
                            JoinDate = new DateTime(2022, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Kumar",
                            Salary = "£52000.00"
                        },
                        new
                        {
                            Id = 6,
                            Department = "Software Engineering",
                            Email = "dzhang@company.com",
                            FirstName = "David",
                            Gender = "Male",
                            JoinDate = new DateTime(2022, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Zhang",
                            Salary = "£63000.00"
                        },
                        new
                        {
                            Id = 7,
                            Department = "Human Resources",
                            Email = "lmartinez@company.com",
                            FirstName = "Lisa",
                            Gender = "Female",
                            JoinDate = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Martinez",
                            Salary = "£48000.00"
                        },
                        new
                        {
                            Id = 8,
                            Department = "Software Engineering",
                            Email = "rsingh@company.com",
                            FirstName = "Robert",
                            Gender = "Male",
                            JoinDate = new DateTime(2023, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Singh",
                            LeaveDate = new DateTime(2024, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Salary = "£64000.00"
                        },
                        new
                        {
                            Id = 9,
                            Department = "Product Management",
                            Email = "mlee@company.com",
                            FirstName = "Michelle",
                            Gender = "Female",
                            JoinDate = new DateTime(2023, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Lee",
                            Salary = "£66000.00"
                        },
                        new
                        {
                            Id = 10,
                            Department = "Sales",
                            Email = "wbrown@company.com",
                            FirstName = "William",
                            Gender = "Male",
                            JoinDate = new DateTime(2023, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Brown",
                            Salary = "£54000.00"
                        },
                        new
                        {
                            Id = 11,
                            Department = "Software Engineering",
                            Email = "ejohnson@company.com",
                            FirstName = "Emma",
                            Gender = "Female",
                            JoinDate = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Johnson",
                            Salary = "£61000.00"
                        },
                        new
                        {
                            Id = 12,
                            Department = "Marketing",
                            Email = "dkim@company.com",
                            FirstName = "Daniel",
                            Gender = "Male",
                            JoinDate = new DateTime(2023, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Kim",
                            LeaveDate = new DateTime(2024, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Salary = "£51000.00"
                        },
                        new
                        {
                            Id = 13,
                            Department = "Software Engineering",
                            Email = "rgarcia@company.com",
                            FirstName = "Rachel",
                            Gender = "Female",
                            JoinDate = new DateTime(2023, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Garcia",
                            Salary = "£63000.00"
                        },
                        new
                        {
                            Id = 14,
                            Department = "Product Management",
                            Email = "tanderson@company.com",
                            FirstName = "Thomas",
                            Gender = "Male",
                            JoinDate = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Anderson",
                            Salary = "£67000.00"
                        },
                        new
                        {
                            Id = 15,
                            Department = "Software Engineering",
                            Email = "swang@company.com",
                            FirstName = "Sophia",
                            Gender = "Female",
                            JoinDate = new DateTime(2023, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Wang",
                            Salary = "£62000.00"
                        },
                        new
                        {
                            Id = 16,
                            Department = "Sales",
                            Email = "ktaylor@company.com",
                            FirstName = "Kevin",
                            Gender = "Male",
                            JoinDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Taylor",
                            Salary = "£56000.00"
                        },
                        new
                        {
                            Id = 17,
                            Department = "Marketing",
                            Email = "arodriguez@company.com",
                            FirstName = "Anna",
                            Gender = "Female",
                            JoinDate = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Rodriguez",
                            Salary = "£53000.00"
                        },
                        new
                        {
                            Id = 18,
                            Department = "Software Engineering",
                            Email = "cgupta@company.com",
                            FirstName = "Christopher",
                            Gender = "Male",
                            JoinDate = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Gupta",
                            LeaveDate = new DateTime(2024, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Salary = "£65000.00"
                        },
                        new
                        {
                            Id = 19,
                            Department = "Human Resources",
                            Email = "anguyen@company.com",
                            FirstName = "Alexandra",
                            Gender = "Female",
                            JoinDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Nguyen",
                            Salary = "£49000.00"
                        },
                        new
                        {
                            Id = 20,
                            Department = "Software Engineering",
                            Email = "rwhite@company.com",
                            FirstName = "Ryan",
                            Gender = "Male",
                            JoinDate = new DateTime(2024, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "White",
                            Salary = "£64000.00"
                        },
                        new
                        {
                            Id = 21,
                            Department = "Product Management",
                            Email = "isantos@company.com",
                            FirstName = "Isabella",
                            Gender = "Female",
                            JoinDate = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Santos",
                            Salary = "£65000.00"
                        },
                        new
                        {
                            Id = 22,
                            Department = "Software Engineering",
                            Email = "jpark@company.com",
                            FirstName = "Jonathan",
                            Gender = "Male",
                            JoinDate = new DateTime(2024, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Park",
                            Salary = "£63000.00"
                        },
                        new
                        {
                            Id = 23,
                            Department = "Marketing",
                            Email = "mcollins@company.com",
                            FirstName = "Maria",
                            Gender = "Female",
                            JoinDate = new DateTime(2024, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Collins",
                            Salary = "£52000.00"
                        },
                        new
                        {
                            Id = 24,
                            Department = "Sales",
                            Email = "amurphy@company.com",
                            FirstName = "Andrew",
                            Gender = "Male",
                            JoinDate = new DateTime(2024, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Murphy",
                            Salary = "£55000.00"
                        },
                        new
                        {
                            Id = 25,
                            Department = "Software Engineering",
                            Email = "jcohen@company.com",
                            FirstName = "Julia",
                            Gender = "Female",
                            JoinDate = new DateTime(2024, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Cohen",
                            Salary = "£61000.00"
                        });
                });

            modelBuilder.Entity("HRApp.Models.TimeOffRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdminComments")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReviewedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("TimeOffRequests");
                });

            modelBuilder.Entity("HRApp.Models.CalendarEvent", b =>
                {
                    b.HasOne("HRApp.Models.Employees", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HRApp.Models.TimeOffRequest", b =>
                {
                    b.HasOne("HRApp.Models.Employees", "Employee")
                        .WithMany("TimeOffRequests")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HRApp.Models.Employees", b =>
                {
                    b.Navigation("TimeOffRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
